import styled from 'styled-components';

export const Container = styled.div`
  width: 100vw;
  height: 100vh;

  position: fixed;
  top: 0;
  left: 0;
  background: rgba(0, 0, 0, 0.2);
  z-index: 999999999999;

  display: flex;
  align-items: center;
  justify-content: center;

  @keyframes ldio-t8u9l4r441r {
    0% {
      transform: translate(-50%, -50%) rotate(0deg);
    }
    100% {
      transform: translate(-50%, -50%) rotate(360deg);
    }
  }
  .ldio-t8u9l4r441r div {
    position: absolute;
    width: 120px;
    height: 120px;
    border: 20px solid var(--orange);
    border-top-color: transparent;
    border-radius: 50%;
  }
  .ldio-t8u9l4r441r div {
    animation: ldio-t8u9l4r441r 1s linear infinite;
    top: 100px;
    left: 100px;
  }
  .loadingio-spinner-rolling-4rnd8mw767j {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
  }
  .ldio-t8u9l4r441r {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-t8u9l4r441r div {
    box-sizing: content-box;
  }
  /* generated by https://loading.io/ */
`;
